/* Generated by gbrecomp */
#ifndef pokeyellow_H
#define pokeyellow_H

#include "gbrt.h"

const GBConfig* pokeyellow_default_config(void);
void pokeyellow_run(GBContext* ctx);
void pokeyellow_init(GBContext* ctx);
int pokeyellow_main(int argc, char* argv[]);

#endif
