/* Generated by gbrecomp from pokeyellow */
#include "pokeyellow_internal.h"
#include "gbrt.h"
#include <stdio.h>
#include <stdlib.h>

/* Bank dispatch - routes calls to the correct bank function */
void pokeyellow_dispatch_00(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_01(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_02(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_03(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_04(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_05(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_06(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_07(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_08(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_09(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_0a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_0b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_0c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_0d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_0e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_0f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_10(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_11(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_12(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_13(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_14(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_15(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_16(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_17(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_18(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_19(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_1a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_1b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_1c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_1d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_1e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_1f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_20(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_21(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_22(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_23(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_24(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_25(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_26(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_27(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_28(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_29(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_2a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_2b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_2c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_2d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_2e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_2f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_30(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_31(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_32(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_33(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_34(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_35(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_36(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_37(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_38(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_39(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_3a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_3b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_3c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_3d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_3e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_3f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_40(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_41(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_42(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_43(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_44(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_45(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_46(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_47(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_48(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_49(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_4a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_4b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_4c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_4d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_4e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_4f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_50(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_51(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_52(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_53(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_54(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_55(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_56(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_57(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_58(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_59(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_5a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_5b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_5c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_5d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_5e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_5f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_60(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_61(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_62(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_63(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_64(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_65(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_66(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_67(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_68(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_69(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_6a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_6b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_6c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_6d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_6e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_6f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_70(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_71(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_72(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_73(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_74(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_75(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_76(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_77(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_78(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_79(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_7a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_7b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_7c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_7d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_7e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_7f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokeyellow_dispatch_ff(GBContext* ctx, uint16_t addr, uint8_t bank);

static uint8_t pokeyellow__ram_overlay_0_matches(GBContext* ctx) {
    if (gb_read8(ctx, 0xff80) != 0x3e) return 0;
    if (gb_read8(ctx, 0xff81) != 0xc3) return 0;
    if (gb_read8(ctx, 0xff82) != 0xe0) return 0;
    if (gb_read8(ctx, 0xff83) != 0x46) return 0;
    if (gb_read8(ctx, 0xff84) != 0x3e) return 0;
    if (gb_read8(ctx, 0xff85) != 0x28) return 0;
    if (gb_read8(ctx, 0xff86) != 0x3d) return 0;
    if (gb_read8(ctx, 0xff87) != 0x20) return 0;
    if (gb_read8(ctx, 0xff88) != 0xfd) return 0;
    if (gb_read8(ctx, 0xff89) != 0xc9) return 0;
    return 1;
}

static uint8_t pokeyellow__try_dispatch_compiled_ram_overlay(GBContext* ctx, uint16_t addr, uint8_t bank) {
    if (addr >= 0xff80 && addr < 0xff8a) {
        if (!pokeyellow__ram_overlay_0_matches(ctx)) {
            return 0;
        }
        switch (addr) {
            case 0xff80:
                pokeyellow_dispatch_ff(ctx, addr, bank);
                return 1;
            default:
                return 0;
        }
    }
    return 0;
}

void pokeyellow__gb_dispatch(GBContext* ctx, uint16_t addr) {
    ctx->pc = addr;
    while (!ctx->stopped && !ctx->halted) {
        addr = ctx->pc;
        uint8_t bank = ctx->rom_bank;
        if (addr < 0x4000) bank = 0;
        if (gbrt_instruction_limit > 0 && gbrt_instruction_count >= gbrt_instruction_limit) {
            fprintf(stderr, "[LIMIT] Reached instruction limit %llu\n", (unsigned long long)gbrt_instruction_limit);
            exit(0);
        }
        gbrt_instruction_count++;
        gbrt_log_trace(ctx, bank, addr);
        if (gbrt_trace_enabled) {
            fprintf(stderr, "[TRACE] Dispatch 0x%04X (Bank %d)\n", addr, bank);
        }
        if (gbrt_try_execute_hram_stub(ctx, addr)) {
            if (ctx->single_step_mode) break;
            continue;
        }
        if (gbrt_try_execute_highmem_stub(ctx, addr)) {
            if (ctx->single_step_mode || ctx->stopped) break;
            continue;
        }
        if (gbrt_try_execute_ram_stub(ctx, addr)) {
            if (ctx->single_step_mode || ctx->stopped) break;
            continue;
        }
        if (pokeyellow__try_dispatch_compiled_ram_overlay(ctx, addr, bank)) {
            if (ctx->single_step_mode || ctx->stopped) break;
            continue;
        }
        if (addr >= 0xFF80 && addr <= 0xFFFE) {
            gbrt_note_dispatch_fallback(ctx, bank, addr);
            gb_interpret(ctx, addr);
            if (ctx->single_step_mode || ctx->stopped) break;
            continue;
        }
        switch (addr >> 8) {
            case 0x00: pokeyellow_dispatch_00(ctx, addr, bank); break;
            case 0x01: pokeyellow_dispatch_01(ctx, addr, bank); break;
            case 0x02: pokeyellow_dispatch_02(ctx, addr, bank); break;
            case 0x03: pokeyellow_dispatch_03(ctx, addr, bank); break;
            case 0x04: pokeyellow_dispatch_04(ctx, addr, bank); break;
            case 0x05: pokeyellow_dispatch_05(ctx, addr, bank); break;
            case 0x06: pokeyellow_dispatch_06(ctx, addr, bank); break;
            case 0x07: pokeyellow_dispatch_07(ctx, addr, bank); break;
            case 0x08: pokeyellow_dispatch_08(ctx, addr, bank); break;
            case 0x09: pokeyellow_dispatch_09(ctx, addr, bank); break;
            case 0x0a: pokeyellow_dispatch_0a(ctx, addr, bank); break;
            case 0x0b: pokeyellow_dispatch_0b(ctx, addr, bank); break;
            case 0x0c: pokeyellow_dispatch_0c(ctx, addr, bank); break;
            case 0x0d: pokeyellow_dispatch_0d(ctx, addr, bank); break;
            case 0x0e: pokeyellow_dispatch_0e(ctx, addr, bank); break;
            case 0x0f: pokeyellow_dispatch_0f(ctx, addr, bank); break;
            case 0x10: pokeyellow_dispatch_10(ctx, addr, bank); break;
            case 0x11: pokeyellow_dispatch_11(ctx, addr, bank); break;
            case 0x12: pokeyellow_dispatch_12(ctx, addr, bank); break;
            case 0x13: pokeyellow_dispatch_13(ctx, addr, bank); break;
            case 0x14: pokeyellow_dispatch_14(ctx, addr, bank); break;
            case 0x15: pokeyellow_dispatch_15(ctx, addr, bank); break;
            case 0x16: pokeyellow_dispatch_16(ctx, addr, bank); break;
            case 0x17: pokeyellow_dispatch_17(ctx, addr, bank); break;
            case 0x18: pokeyellow_dispatch_18(ctx, addr, bank); break;
            case 0x19: pokeyellow_dispatch_19(ctx, addr, bank); break;
            case 0x1a: pokeyellow_dispatch_1a(ctx, addr, bank); break;
            case 0x1b: pokeyellow_dispatch_1b(ctx, addr, bank); break;
            case 0x1c: pokeyellow_dispatch_1c(ctx, addr, bank); break;
            case 0x1d: pokeyellow_dispatch_1d(ctx, addr, bank); break;
            case 0x1e: pokeyellow_dispatch_1e(ctx, addr, bank); break;
            case 0x1f: pokeyellow_dispatch_1f(ctx, addr, bank); break;
            case 0x20: pokeyellow_dispatch_20(ctx, addr, bank); break;
            case 0x21: pokeyellow_dispatch_21(ctx, addr, bank); break;
            case 0x22: pokeyellow_dispatch_22(ctx, addr, bank); break;
            case 0x23: pokeyellow_dispatch_23(ctx, addr, bank); break;
            case 0x24: pokeyellow_dispatch_24(ctx, addr, bank); break;
            case 0x25: pokeyellow_dispatch_25(ctx, addr, bank); break;
            case 0x26: pokeyellow_dispatch_26(ctx, addr, bank); break;
            case 0x27: pokeyellow_dispatch_27(ctx, addr, bank); break;
            case 0x28: pokeyellow_dispatch_28(ctx, addr, bank); break;
            case 0x29: pokeyellow_dispatch_29(ctx, addr, bank); break;
            case 0x2a: pokeyellow_dispatch_2a(ctx, addr, bank); break;
            case 0x2b: pokeyellow_dispatch_2b(ctx, addr, bank); break;
            case 0x2c: pokeyellow_dispatch_2c(ctx, addr, bank); break;
            case 0x2d: pokeyellow_dispatch_2d(ctx, addr, bank); break;
            case 0x2e: pokeyellow_dispatch_2e(ctx, addr, bank); break;
            case 0x2f: pokeyellow_dispatch_2f(ctx, addr, bank); break;
            case 0x30: pokeyellow_dispatch_30(ctx, addr, bank); break;
            case 0x31: pokeyellow_dispatch_31(ctx, addr, bank); break;
            case 0x32: pokeyellow_dispatch_32(ctx, addr, bank); break;
            case 0x33: pokeyellow_dispatch_33(ctx, addr, bank); break;
            case 0x34: pokeyellow_dispatch_34(ctx, addr, bank); break;
            case 0x35: pokeyellow_dispatch_35(ctx, addr, bank); break;
            case 0x36: pokeyellow_dispatch_36(ctx, addr, bank); break;
            case 0x37: pokeyellow_dispatch_37(ctx, addr, bank); break;
            case 0x38: pokeyellow_dispatch_38(ctx, addr, bank); break;
            case 0x39: pokeyellow_dispatch_39(ctx, addr, bank); break;
            case 0x3a: pokeyellow_dispatch_3a(ctx, addr, bank); break;
            case 0x3b: pokeyellow_dispatch_3b(ctx, addr, bank); break;
            case 0x3c: pokeyellow_dispatch_3c(ctx, addr, bank); break;
            case 0x3d: pokeyellow_dispatch_3d(ctx, addr, bank); break;
            case 0x3e: pokeyellow_dispatch_3e(ctx, addr, bank); break;
            case 0x3f: pokeyellow_dispatch_3f(ctx, addr, bank); break;
            case 0x40: pokeyellow_dispatch_40(ctx, addr, bank); break;
            case 0x41: pokeyellow_dispatch_41(ctx, addr, bank); break;
            case 0x42: pokeyellow_dispatch_42(ctx, addr, bank); break;
            case 0x43: pokeyellow_dispatch_43(ctx, addr, bank); break;
            case 0x44: pokeyellow_dispatch_44(ctx, addr, bank); break;
            case 0x45: pokeyellow_dispatch_45(ctx, addr, bank); break;
            case 0x46: pokeyellow_dispatch_46(ctx, addr, bank); break;
            case 0x47: pokeyellow_dispatch_47(ctx, addr, bank); break;
            case 0x48: pokeyellow_dispatch_48(ctx, addr, bank); break;
            case 0x49: pokeyellow_dispatch_49(ctx, addr, bank); break;
            case 0x4a: pokeyellow_dispatch_4a(ctx, addr, bank); break;
            case 0x4b: pokeyellow_dispatch_4b(ctx, addr, bank); break;
            case 0x4c: pokeyellow_dispatch_4c(ctx, addr, bank); break;
            case 0x4d: pokeyellow_dispatch_4d(ctx, addr, bank); break;
            case 0x4e: pokeyellow_dispatch_4e(ctx, addr, bank); break;
            case 0x4f: pokeyellow_dispatch_4f(ctx, addr, bank); break;
            case 0x50: pokeyellow_dispatch_50(ctx, addr, bank); break;
            case 0x51: pokeyellow_dispatch_51(ctx, addr, bank); break;
            case 0x52: pokeyellow_dispatch_52(ctx, addr, bank); break;
            case 0x53: pokeyellow_dispatch_53(ctx, addr, bank); break;
            case 0x54: pokeyellow_dispatch_54(ctx, addr, bank); break;
            case 0x55: pokeyellow_dispatch_55(ctx, addr, bank); break;
            case 0x56: pokeyellow_dispatch_56(ctx, addr, bank); break;
            case 0x57: pokeyellow_dispatch_57(ctx, addr, bank); break;
            case 0x58: pokeyellow_dispatch_58(ctx, addr, bank); break;
            case 0x59: pokeyellow_dispatch_59(ctx, addr, bank); break;
            case 0x5a: pokeyellow_dispatch_5a(ctx, addr, bank); break;
            case 0x5b: pokeyellow_dispatch_5b(ctx, addr, bank); break;
            case 0x5c: pokeyellow_dispatch_5c(ctx, addr, bank); break;
            case 0x5d: pokeyellow_dispatch_5d(ctx, addr, bank); break;
            case 0x5e: pokeyellow_dispatch_5e(ctx, addr, bank); break;
            case 0x5f: pokeyellow_dispatch_5f(ctx, addr, bank); break;
            case 0x60: pokeyellow_dispatch_60(ctx, addr, bank); break;
            case 0x61: pokeyellow_dispatch_61(ctx, addr, bank); break;
            case 0x62: pokeyellow_dispatch_62(ctx, addr, bank); break;
            case 0x63: pokeyellow_dispatch_63(ctx, addr, bank); break;
            case 0x64: pokeyellow_dispatch_64(ctx, addr, bank); break;
            case 0x65: pokeyellow_dispatch_65(ctx, addr, bank); break;
            case 0x66: pokeyellow_dispatch_66(ctx, addr, bank); break;
            case 0x67: pokeyellow_dispatch_67(ctx, addr, bank); break;
            case 0x68: pokeyellow_dispatch_68(ctx, addr, bank); break;
            case 0x69: pokeyellow_dispatch_69(ctx, addr, bank); break;
            case 0x6a: pokeyellow_dispatch_6a(ctx, addr, bank); break;
            case 0x6b: pokeyellow_dispatch_6b(ctx, addr, bank); break;
            case 0x6c: pokeyellow_dispatch_6c(ctx, addr, bank); break;
            case 0x6d: pokeyellow_dispatch_6d(ctx, addr, bank); break;
            case 0x6e: pokeyellow_dispatch_6e(ctx, addr, bank); break;
            case 0x6f: pokeyellow_dispatch_6f(ctx, addr, bank); break;
            case 0x70: pokeyellow_dispatch_70(ctx, addr, bank); break;
            case 0x71: pokeyellow_dispatch_71(ctx, addr, bank); break;
            case 0x72: pokeyellow_dispatch_72(ctx, addr, bank); break;
            case 0x73: pokeyellow_dispatch_73(ctx, addr, bank); break;
            case 0x74: pokeyellow_dispatch_74(ctx, addr, bank); break;
            case 0x75: pokeyellow_dispatch_75(ctx, addr, bank); break;
            case 0x76: pokeyellow_dispatch_76(ctx, addr, bank); break;
            case 0x77: pokeyellow_dispatch_77(ctx, addr, bank); break;
            case 0x78: pokeyellow_dispatch_78(ctx, addr, bank); break;
            case 0x79: pokeyellow_dispatch_79(ctx, addr, bank); break;
            case 0x7a: pokeyellow_dispatch_7a(ctx, addr, bank); break;
            case 0x7b: pokeyellow_dispatch_7b(ctx, addr, bank); break;
            case 0x7c: pokeyellow_dispatch_7c(ctx, addr, bank); break;
            case 0x7d: pokeyellow_dispatch_7d(ctx, addr, bank); break;
            case 0x7e: pokeyellow_dispatch_7e(ctx, addr, bank); break;
            case 0x7f: pokeyellow_dispatch_7f(ctx, addr, bank); break;
            case 0xff: pokeyellow_dispatch_ff(ctx, addr, bank); break;
            default: gbrt_note_dispatch_fallback(ctx, bank, addr); gb_interpret(ctx, addr); break;
        }
        if (ctx->single_step_mode) break;
    }
}

void pokeyellow__gb_dispatch_call(GBContext* ctx, uint16_t addr) {
    pokeyellow__gb_dispatch(ctx, addr);
}

/* Extern reference to ROM data */
extern uint8_t pokeyellow__rom_data[];
extern const size_t pokeyellow__rom_size;

const GBConfig* pokeyellow_default_config(void) {
    static const GBConfig config = {
        .model = GB_MODEL_CGB,
        .cgb_compatibility_mode = false,
        .cartridge_supports_cgb = true,
        .cartridge_requires_cgb = false,
        .enable_bootrom = false,
        .enable_audio = true,
        .enable_serial = true,
        .speed_percent = 100,
    };
    return &config;
}

void pokeyellow_init(GBContext* ctx) {
    /* Load ROM data into context */
    gb_context_load_rom(ctx, pokeyellow__rom_data, pokeyellow__rom_size);
    /* Set MBC type from header */
    ctx->mbc_type = pokeyellow__rom_data[0x147];
    gb_context_reset(ctx, true);
}

void pokeyellow_run(GBContext* ctx) {
    // Start the trampoline loop - execution will stay here until stopped
    pokeyellow__gb_dispatch(ctx, ctx->pc);
}
